apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJMV0lnWW5KbFlXUnliMk5yTVRwbmFYUm9kV0pmY0dGMFh6RXhRVWhWV0ZSVFNUQlZabGQyUjBWaE1ISlNSMGxmUVhaRmJubDBZVzF2Um1KeWEwNUNaa1ZzU0VKS1pUUllkM2M1VVZKM1IzRmFXR3BsVTJ0NFZXNVFRVWxUVlVsWldrOUZVR1J0U2pCYVNVY0siCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
